import Head from 'next/head';
import dynamic from 'next/dynamic';
import Aos from 'aos';

import { useEffect } from 'react';

const Header = dynamic(() => import('../../components/Header'));
const Built = dynamic(() => import('../../components/Built'));
const Suits = dynamic(() => import('../../components/Suits'));
const Footer = dynamic(() => import('../../components/Footer'));

export default function Home() {
  // animate on scroll initialization
  useEffect(() => {
    Aos.init({
      easing: 'ease-out-cubic',
      once: true,
      duration: 1800,
      offset: 0,
    });
  }, []);

  return (
    <>
      <Head>
        <title>NiagaPay - Solution For Payments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-7xl mx-auto overflow-hidden">
        <Header />
        <main className="max-w-7xl mx-auto px-8">
          <Built />
          <Suits />
        </main>
        <Footer />
      </div>
    </>
  );
}
